=BDS("FUND_SEARCH","FULL_FUND_NAME,TICKER,FUND_CURRENCY","FUND_NAME_SEARCH_STRING="&A1)
=BDS("FUND_SEARCH","TICKER","FUND_NAME="&A1)
=BDS("FSRC","FUND_TICKER,FUND_NAME","SEARCH_STRING="&A1)
=BDS("FSRC","FUND_TICKER,FUND_NAME","SEARCH_STRING="""&A1&"""")
